name: Contract test runner
description: "Reusable contract runner action"
inputs:
  cargo-flags:
    description: "Flags to pass to cargo commands."
    required: true
  token:
    description: "GH Token used for retrieving SDK test harness."
    required: true

runs:
  using: composite
  steps:
    - name: Build contract tests
      shell: bash
      run: CARGO_FLAGS="${{ inputs.cargo-flags }}" make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: CARGO_FLAGS="${{ inputs.cargo-flags }}" make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.2
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        extra_params: "-skip-from ./contract-tests/testharness-suppressions.txt"
