name: Contract test runner
description: 'Reusable contract runner action'
inputs:
  tls_feature:
    description: 'Which TLS feature do you want to enable?'
    required: true

runs:
  using: composite
  steps:
    - name: Build contract tests
      shell: bash
      run: TLS_FEATURE=${{ input.tls_feature }} make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: make start-contract-test-service-bg

    - name: Run contract tests
      shell: bash
      run: make run-contract-tests
