name: Contract test runner
description: 'Reusable contract runner action'
inputs:
  tls_feature:
    description: 'Which TLS feature do you want to enable?'
    required: true
  token:
    description: 'GH Token used for retrieving SDK test harness.'
    required: true

runs:
  using: composite
  steps:
    - name: Build contract tests
      shell: bash
      run: TLS_FEATURE="${{ inputs.tls_feature }}" make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.1
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        extra_params: "-skip-from ./contract-tests/testharness-suppressions.txt"
