[package]
name = "ldclient"
version = "0.1.0"
authors = ["Sam Stokes <sstokes@launchdarkly.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
log = "0.4.6"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
tokio = "0.1.16"

[dependencies.eventsource-client]
path = "../rust-eventsource-client"

[dev-dependencies]
maplit = "1.0.1"
simplelog = "0.5.3"
spectral = "0.6.0"
