[package]
name = "ldclient"
version = "0.1.0"
authors = ["Sam Stokes <sstokes@launchdarkly.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
eventsource-client = "0.3.1"
futures = "0.1.25"
http = ">= 0.1.18"
lazy_static = "1.4.0"
log = "0.4.6"
lru = { version = "0.5.3", default_features = false }
regex = "1"
reqwest = "0.9.11"
semver = "0.10.0"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
sha1 = { version = "0.6.0", features = ["std"] }
thiserror = "1.0"
tokio = "0.1.16"

[dev-dependencies]
maplit = "1.0.1"
env_logger = "0.7.1"
spectral = "0.6.0"
cursive = "0.11"
tokio-executor = "0.1.6"

[build-dependencies]
built = "0.4"
