[package]
name = "ldclient"
version = "0.1.0"
authors = ["Sam Stokes <sstokes@launchdarkly.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
reqwest = "0.9.11"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
tokio = "0.1.16"
